# Generated by Django 3.1.7 on 2021-03-07 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20210307_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2, verbose_name='Género')),
                ('medical_history_number', models.CharField(blank=True, max_length=50, verbose_name='Número de historia clínica')),
                ('dni', models.CharField(max_length=12, verbose_name='DNI')),
                ('date_birth', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('degree', models.CharField(choices=[('AN', 'Analfabeto'), ('PI', 'Primaria Incompleta'), ('PC', 'Primaria Completa'), ('SI', 'Secundaria Incompleta'), ('SC', 'Secundaria Completa'), ('MI', 'Superior Incompleta'), ('MC', 'Superior Completa')], max_length=2, verbose_name='Grado de Instrucción')),
                ('marital_status', models.CharField(choices=[('SO', 'Soltero'), ('CO', 'Conviviente'), ('CA', 'Casado'), ('DI', 'Divorciado'), ('VI', 'Viudo')], max_length=2, verbose_name='Estado Civil')),
                ('occupation', models.CharField(blank=True, max_length=255, verbose_name='Ocupación')),
                ('religion', models.CharField(blank=True, max_length=255, verbose_name='Religion')),
                ('ethnicity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ethnicity', verbose_name='Etnia')),
                ('phone', models.ManyToManyField(blank=True, to='core.Phone', verbose_name='Números de telefono')),
                ('place_birth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pb_filiations', to='core.ubigeo', verbose_name='Lugar de Nacimiento')),
                ('place_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_filiations', to='core.ubigeo', verbose_name='Lugar de Prodencia')),
            ],
        ),
        migrations.CreateModel(
            name='GinecologyComplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aplica')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('is_custom', models.BooleanField(default=True, verbose_name='Personalizada')),
            ],
        ),
        migrations.CreateModel(
            name='GynecologicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_complications', models.ManyToManyField(related_name='bc_histories', to='patient.GinecologyComplication', verbose_name='Complicaciones durante el parto ')),
                ('obstetric_gyneco_history', models.ManyToManyField(to='core.ItemModel', verbose_name='Antecedentes gineco-obstetricos')),
                ('pregnancy_complications', models.ManyToManyField(related_name='pc_histories', to='patient.GinecologyComplication', verbose_name='Complicaciones durante la Gestación')),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('itemmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.itemmodel')),
                ('immunization_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('observation', models.CharField(blank=True, max_length=1255, verbose_name='Observación ')),
            ],
            bases=('core.itemmodel',),
        ),
        migrations.CreateModel(
            name='ItemComorbidity',
            fields=[
                ('itemmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.itemmodel')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de fin')),
                ('treatment', models.CharField(blank=True, max_length=1275, verbose_name='Tratamiento')),
            ],
            bases=('core.itemmodel',),
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aplica')),
                ('death_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Muerte')),
                ('disease', models.CharField(blank=True, max_length=255, verbose_name='Enfermedad')),
                ('cause', models.CharField(blank=True, max_length=1275, verbose_name='Causa de muerte')),
            ],
        ),
        migrations.CreateModel(
            name='ToxicHabit',
            fields=[
                ('itemmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.itemmodel')),
                ('moment', models.CharField(choices=[('An', 'Antes'), ('Ac', 'Actual')], max_length=2, verbose_name='Momento del hábito')),
            ],
            bases=('core.itemmodel',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergic_reactions', models.ManyToManyField(related_name='ar_patients', to='core.BooleanText', verbose_name='Reacciones alergica')),
                ('comorbidity', models.ManyToManyField(to='patient.ItemComorbidity', verbose_name='Comorbilidad')),
                ('family_autoimmune_diseases', models.ManyToManyField(related_name='fad_patients', to='core.BooleanText', verbose_name='Antecedentes de Enfermedades autoinmunes en familiares')),
                ('filiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.filiation', verbose_name='Filiación')),
                ('gyneco_obstetric_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.gynecologicalhistory', verbose_name='Antecedentes Gineco-obstetricos')),
                ('immunizations', models.ManyToManyField(to='patient.Immunization', verbose_name='Inmunizaciones')),
                ('mortality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.mortality', verbose_name='Mortalidad')),
                ('toxic_habits', models.ManyToManyField(to='patient.ToxicHabit', verbose_name='Hábitos tóxicos')),
            ],
            options={
                'verbose_name': 'Paciente',
            },
        ),
    ]
