FROM python:3.8-slim-buster

WORKDIR /app
COPY ./reumadata_backend/. /app/reumadata_backend

# Install poetry:
RUN pip install --upgrade pip
RUN pip install poetry

# Copy in the config files:
COPY pyproject.toml poetry.lock ./
# Copy in the config files:
COPY ./docker/start.sh /app/start.sh
# Install only dependencies:
RUN poetry install --no-root --no-dev

# Copy in everything else and install:
RUN poetry install --no-dev
CMD ["./start.sh"]