# Generated by Django 3.1.7 on 2021-03-07 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aplica')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('description', models.CharField(blank=True, max_length=1275, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Etnia')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Aplica?')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('is_custom', models.BooleanField(default=True, verbose_name='¿Es personalizada?')),
                ('value', models.IntegerField(default=0, verbose_name='Tiempo o valor')),
                ('value_type', models.CharField(choices=[('D', 'Dias'), ('M', 'Meses'), ('A', 'Años'), ('U', 'Unidades')], max_length=2, verbose_name='Unidad de medida')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='Número de teléfono')),
                ('type', models.CharField(choices=[('C', 'Celular'), ('F', 'Fijo')], max_length=2, verbose_name='Tipo de número telefónico')),
            ],
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Departamento'),
        ),
    ]
